# Generated by Django 4.2.5 on 2023-09-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Expenses', 'verbose_name_plural': 'Expenses'},
        ),
    ]
